title: DocuTheme
description: A clean, modern documentation theme for Jekyll.
# Add your logo path here:
logo: /assets/images/logo.svg

theme: null
markdown: kramdown

# Optional, but nice:
permalink: pretty