title: DocuTheme
description: A clean, modern documentation theme for Jekyll.
logo: /assets/images/logo.svg

# --- UI Icons ---
toc_icon: "‚ò∞"
theme_icon_light: "üåô"  # Icon to show when switching TO light mode
theme_icon_dark: "‚òÄÔ∏è"   # Icon to show when switching TO dark mode

theme: null
markdown: kramdown

# Optional, but nice:

permalink: pretty
