title: DocuTheme
description: A clean, modern documentation theme for Jekyll.
logo: /assets/images/logo.svg

# UI Icons
toc_icon: "‚ò∞"
theme_icon_light: "üåô"  # Icon shown when switching TO light mode
theme_icon_dark: "‚òÄÔ∏è"   # Icon shown when switching TO dark mode

# Automatic Layouts (Optional, but recommended)
defaults:
  - scope:
      path: ""
    values:
      layout: "default"


theme: null
markdown: kramdown

# Optional, but nice:

permalink: pretty
